builds:
  - binary: ocdev
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

release:
  github:
    owner: kadel
    name: ocdev

  draft: true
  prerelease: true

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}}"